<!--
   ~ Licensed to the Apache Software Foundation (ASF) under one
   ~ or more contributor license agreements.  See the NOTICE file
   ~ distributed with this work for additional information
   ~ regarding copyright ownership.  The ASF licenses this file
   ~ to you under the Apache License, Version 2.0 (the
   ~ "License"); you may not use this file except in compliance
   ~ with the License.  You may obtain a copy of the License at
   ~
   ~    http://www.apache.org/licenses/LICENSE-2.0
   ~
   ~ Unless required by applicable law or agreed to in writing,
   ~ software distributed under the License is distributed on an
   ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   ~ KIND, either express or implied.  See the License for the
   ~ specific language governing permissions and limitations
   ~ under the License.
-->

<wsdl:definitions targetNamespace="http://ode/bpel/unit-test/FaultService.wsdl"
   xmlns="http://ode/bpel/unit-test/FaultService.wsdl"
   xmlns:tns="http://ode/bpel/unit-test/FaultService.wsdl"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">

   <wsdl:message name="faultMessage">
      <wsdl:part name="faultName" type="xsd:string"/>
      <wsdl:part name="faultData" type="xsd:string"/>
      <wsdl:part name="faultIndicator1" type="xsd:string"/>
      <wsdl:part name="faultIndicator2" type="xsd:string"/>
   </wsdl:message>
   <wsdl:message name="errorMessage">
      <wsdl:part name="errorID" type="xsd:string"/>
      <wsdl:part name="errorText" type="xsd:string"/>
   </wsdl:message>

    <wsdl:portType name="faultMessagePT">
      <wsdl:operation name="throwFault">
         <wsdl:input name="FaultInputMessage" message="tns:faultMessage"/>
         <wsdl:output name="FaultOutputMessage" message="tns:faultMessage"/>
         <wsdl:fault name="FaultMessage1" message="tns:errorMessage"/>
         <wsdl:fault name="FaultMessage2" message="tns:errorMessage"/>
         <wsdl:fault name="UnknownFault" message="tns:errorMessage"/>
      </wsdl:operation>
   </wsdl:portType>

</wsdl:definitions>

