<?xml version="1.0"?>
<wsdl:definitions targetNamespace="http://ode/bpel/unit-test.wsdl"
		  xmlns="http://schemas.xmlsoap.org/wsdl/"
		  xmlns:tns="http://ode/bpel/unit-test.wsdl"
		  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
		  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		  xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
		  xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   
  
  <wsdl:message name="TestMessage">
    <wsdl:part name="TestPart" type="xsd:int"/>
  </wsdl:message>
  
  <wsdl:portType name="TestPortType">
    <wsdl:operation name="testOperation">
      <wsdl:input message="tns:TestMessage" name="TestIn"/>
      <wsdl:output message="tns:TestMessage" name="TestOut"/>
    </wsdl:operation>    
  </wsdl:portType> 
  
  <bpws:property name="testProp"
		 type="xsd:string"/>
  <plnk:partnerLinkType name="TestPartnerLinkType">
    <plnk:role name="me">
      <plnk:portType name="tns:TestPortType"/>
    </plnk:role>
    <plnk:role name="you">
      <plnk:portType name="tns:TestPortType"/>
    </plnk:role>
  </plnk:partnerLinkType>
</wsdl:definitions>