<?xml version="1.0" encoding="utf-8"?>
<definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://loans.org/wsdl/loan-approval"
	targetNamespace="http://loans.org/wsdl/loan-approval" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns="http://schemas.xmlsoap.org/wsdl/">
	<import
		namespace="http://loans.org/wsdl/loan-approval"
		location="LoanApprovalAbstract.wsdl"/>
	<types/>
    <binding name="LoanSoapBinding" type="tns:loanServicePT">
      <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" /> 
      <operation name="request1">
        <soap:operation soapAction="" style="rpc" /> 
        <input>
          <soap:body use="literal" namespace="http://loans.org/wsdl/loan-approval" /> 
        </input>
      </operation>
      <operation name="request2">
        <soap:operation soapAction="" style="rpc" /> 
        <input>
          <soap:body use="literal" namespace="http://loans.org/wsdl/loan-approval" /> 
        </input>
      </operation>
      <operation name="request3">
        <soap:operation soapAction="" style="rpc" /> 
        <input>
          <soap:body use="literal" namespace="http://loans.org/wsdl/loan-approval" /> 
        </input>
        <output>
          <soap:body use="literal" namespace="http://loans.org/wsdl/loan-approval" /> 
        </output>
      </operation>
	</binding>
	
	<service name="LoanService">
		<port name="LoanPort" binding="tns:LoanSoapBinding">
			<soap:address location="http://this/is/ignored"/>
		</port>
	</service>
</definitions>