<?xml version="1.0" encoding="utf-8" ?>

<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<wsdl:definitions
    targetNamespace="http://ode/bpel/unit-test.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://ode/bpel/unit-test.wsdl"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
    xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   
   
    <wsdl:message name="TestMessage1">
        <wsdl:part name="TestPart" type="xsd:string"/>
    </wsdl:message>
    <wsdl:message name="TestMessage2">
        <wsdl:part name="TestPart" type="xsd:int"/>
    </wsdl:message>
    <wsdl:portType name="TestPortType">
        <wsdl:operation name="testOperation">
            <wsdl:input message="tns:TestMessage1" name="TestIn"/>
            <wsdl:output message="tns:TestMessage1" name="TestOut"/>
        </wsdl:operation>    
    </wsdl:portType> 
   <bpws:property name="testProp"
                   type="xsd:string"/>
   <plnk:partnerLinkType name="TestPartnerLinkType">
       <plnk:role name="me">
           <plnk:portType name="tns:TestPortType"/>
       </plnk:role>
       <plnk:role name="you">
           <plnk:portType name="tns:TestPortType"/>
       </plnk:role>
    </plnk:partnerLinkType>
    
   
</wsdl:definitions>

