<?xml version='1.0' encoding='utf-8'?><!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<wsdl:definitions xmlns:tns="http://www.example.org/message" xmlns:Client="http://example.com/helloworld/Client" xmlns:diag="http://example.com/helloworld" xmlns:bpel="http://schemas.xmlsoap.org/ws/2004/03/business-process/" xmlns:pnlk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:this="http://example.com/helloworld/Server" targetNamespace="http://example.com/helloworld/Server">
    <wsdl:types>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://example.com/helloworld/Server">
            <xs:element name="receiveRequest" type="xs:string"/>
            <xs:element name="receiveResponse" type="xs:string"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="receiveRequest">
        <wsdl:part name="body" element="this:receiveRequest"/>
    </wsdl:message>
    <wsdl:message name="receiveResponse">
        <wsdl:part name="body" element="this:receiveResponse"/>
    </wsdl:message>
    <wsdl:portType name="ForClient">
        <wsdl:operation name="receive">
            <wsdl:input message="this:receiveRequest" name="receive"/>
            <wsdl:output message="this:receiveResponse" name="receiveResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CanonicBindingForClient" type="this:ForClient">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="receive">
            <soap:operation style="document" soapAction="http://example.com/helloworld/Server/ForClient/receive"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CanonicServiceForClient">
        <wsdl:port name="canonicPort" binding="this:CanonicBindingForClient">
            <soap:address location="http://localhost:8080/ode/processes/HelloWorld/helloworld/Server/Client"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>