<!--
   ~ Licensed to the Apache Software Foundation (ASF) under one
   ~ or more contributor license agreements.  See the NOTICE file
   ~ distributed with this work for additional information
   ~ regarding copyright ownership.  The ASF licenses this file
   ~ to you under the Apache License, Version 2.0 (the
   ~ "License"); you may not use this file except in compliance
   ~ with the License.  You may obtain a copy of the License at
   ~
   ~    http://www.apache.org/licenses/LICENSE-2.0
   ~
   ~ Unless required by applicable law or agreed to in writing,
   ~ software distributed under the License is distributed on an
   ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
   ~ KIND, either express or implied.  See the License for the
   ~ specific language governing permissions and limitations
   ~ under the License.
-->

<wsdl:definitions 
   targetNamespace="http://ode/bpel/unit-test/TestSimpleVariableType.wsdl"
   xmlns:tns="http://ode/bpel/unit-test/TestSimpleVariableType.wsdl"
   xmlns="http://ode/bpel/unit-test/TestSimpleVariableType.wsdl"
   xmlns:prb="http://ode/bpel/unit-test/ProbeService.wsdl"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"      
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop">


   <wsdl:message name="requestMessage">
      <wsdl:part name="requestID" type="xsd:string"/>
      <wsdl:part name="requestText" type="xsd:string"/>
   </wsdl:message>
   
   <wsdl:message name="replyMessage">
      <wsdl:part name="replyID" type="xsd:string"/>
      <wsdl:part name="replyText" type="xsd:string"/>
   </wsdl:message>
   
   <wsdl:portType name="TestSimpleVariableTypePT">
      <wsdl:operation name="request">
         <wsdl:input message="requestMessage"/>
         <wsdl:output message="replyMessage"/>
      </wsdl:operation>
   </wsdl:portType>

   <wsdl:binding name="TestSimpleVariableTypeBinding" type="tns:TestSimpleVariableTypePT">
      <wsdl:operation name="request">
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="TestSimpleVariableTypeService">
      <wsdl:port name="TestSimpleVariableTypePort" binding="tns:TestSimpleVariableTypeBinding">
      </wsdl:port>
   </wsdl:service>

   <vprop:property name="testProbeID" type="xsd:string"/>
   <vprop:propertyAlias propertyName="tns:testProbeID" messageType="tns:requestMessage" part="requestID"/>

   <plnk:partnerLinkType name="TestSimpleVariableTypeRequest">
      <plnk:role name="TestSimpleVariableTypeService" portType="TestSimpleVariableTypePT"/>
   </plnk:partnerLinkType>

   <plnk:partnerLinkType name="probeRequest">
	<plnk:role name="probeService" portType="prb:probeMessagePT"/>
   </plnk:partnerLinkType>

</wsdl:definitions>
