/* Generated By:JJTree: Do not edit this line. ASTInValues.java */

package org.apache.ode.ql.jcc;

public class ASTInValues extends SimpleNode {
  public ASTInValues(int id) {
    super(id);
  }

  public ASTInValues(QLParser p, int id) {
    super(p, id);
  }

}
