/* Generated By:JJTree: Do not edit this line. ASTIn.java */

package org.apache.ode.ql.jcc;

public class ASTIn extends SimpleNode {
  public ASTIn(int id) {
    super(id);
  }

  public ASTIn(QLParser p, int id) {
    super(p, id);
  }

}
