/* Generated By:JJTree: Do not edit this line. ASTStart.java */

package org.apache.ode.ql.jcc;

public class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(QLParser p, int id) {
    super(p, id);
  }

}
