<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<definitions xmlns:s="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://GeoIpService.wsdl"
    targetNamespace="http://GeoIpService.wsdl" 
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" 
    xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    xmlns:wsn="http://www.webservicex.net">
    
    <import namespace="http://www.webservicex.net" 
            location="http://www.webservicex.net/geoipservice.asmx?WSDL"/>
    
    
    <service name="GeoIpProxy">
        <documentation>A proxy to the GeoIP service</documentation>
        <port name="GeoIpSoap" binding="wsn:GeoIPServiceSoap">
            <soap:address location="http://localhost:@ODE_HTTP_PORT@/ode/soap/geoIp"/>
        </port>
    </service>

    <plnk:partnerLinkType name="GeoIpServiceLinkType">
        <plnk:role name="inbound">
            <plnk:portType name="wsn:GeoIPServiceSoap"/>
        </plnk:role>
        <plnk:role name="outbound">
            <plnk:portType name="wsn:GeoIPServiceSoap"/>
        </plnk:role>
    </plnk:partnerLinkType>

</definitions>
