<?xml version="1.0" encoding="utf-8" ?>

<wsdl:definitions 
    targetNamespace="http://ode/bpel/unit-test.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://ode/bpel/unit-test.wsdl"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:bpws="http://schemas.xmlsoap.org/ws/2004/03/business-process/"
    xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/">
    
     
    <wsdl:import 
      namespace="http://ode/bpel/unit-test.wsdl"
      location="dir11/foo.wsdl" />
      
</wsdl:definitions>

