<?xml version="1.0" encoding="utf-8" ?>

<wsdl:definitions 
    targetNamespace="http://pxe/test/compile.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://pxe/test/compile.wsdl"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
    xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   
    <wsdl:message name="TestMessage">
        <wsdl:part name="TestPart" type="xsd:string"/>
    </wsdl:message>
    <wsdl:portType name="TestPortType">
        <wsdl:operation name="testOperation">
            <wsdl:input message="tns:TestMessage" name="TestIn"/>
            <wsdl:output message="tns:TestMessage" name="TestOut"/>
        </wsdl:operation>    
    </wsdl:portType> 
</wsdl:definitions>

