<!--
bcprt
This software and related documentation are proprietary to UGS Corp.
COPYRIGHT 2005 UGS CORP.  ALL RIGHTS RESERVED
ecprt
-->

<wsdl:definitions name="test"
                  targetNamespace="http://xxx/yyy/ws"
                  xmlns="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:test="http://xxx/yyy"
                  xmlns:testws="http://xxx/yyy/ws"
                  xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">

    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://xxx/yyy" schemaLocation="test.xsd"/>
        </xsd:schema>
    </wsdl:types>

   <wsdl:message name="test-request-msg">
      <wsdl:part name="test-req-part" element="test:test-request"/>
   </wsdl:message>

   <wsdl:message name="test-response-msg">
      <wsdl:part name="test-resp-part" element="test:test-response"/>
   </wsdl:message>

   <wsdl:portType name="testInterface">
      <wsdl:documentation>
           Test BPEL webservice.
      </wsdl:documentation>

      <!-- test operation -->
      <wsdl:operation name="test-op">
         <wsdl:input name="test-op-input"
                     message="testws:test-request-msg"/>
         <wsdl:output name="test-op-output"
                      message="testws:test-response-msg"/>
      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="testBinding" type="testws:testInterface">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="test-op">
           <soap:operation style="document" soapAction="testSoapAction"/>
           <wsdl:input><soap:body  use="literal"/></wsdl:input>
           <wsdl:output><soap:body use="literal"/></wsdl:output>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="testService">
       <wsdl:port binding="testws:testBinding" name="testPort">
          <soap:address location="http://localhost:8080/ode/processes/test"/>
      </wsdl:port>
   </wsdl:service>

  <plnk:partnerLinkType name="test-plt">
     <plnk:role name="testService" portType="testws:testInterface"/>
  </plnk:partnerLinkType>

</wsdl:definitions>
