<?xml version="1.0"?>
<wsdl:definitions targetNamespace="foo://fneh" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="bar://baz/qux" location="deep_wsdl_inner2.wsdl" />
</wsdl:definitions>