<?xml version="1.0"?>
<wsdl:definitions targetNamespace="foo://fneh" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="foo://bar/baz" location="good_xml_not_wsdl.wsdl" />
</wsdl:definitions>
