<?xml version="1.0"?>
<definitions
  targetNamespace="foo://bar/baz"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<types>
		<xs:schema>
			<xs:import namespace="bar://baz/qux" schemaLocation="good_import.xsd"/>
		</xs:schema>
	</types>
	
</definitions>
