<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->

<definitions
   name="Process"
   targetNamespace="uri:com.bptest.process"
   xmlns:proc="uri:com.bptest.process"
   xmlns:typ="uri:com.bptest.types"
   xmlns:resp="uri:com.bptest.responder"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/"
   xmlns="http://schemas.xmlsoap.org/wsdl/">

   <types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="uri:com.bptest.types" schemaLocation="types.xsd"/>
      </schema>
   </types>

   <import namespace="uri:com.bptest.responder"
           location="responder.wsdl"/>

   <message name="ProcessInputMessage">
      <part name="payload" element="typ:AllOrders"/>
   </message>

   <message name="ProcessOutputMessage">
      <part name="payload" element="typ:AllOrders"/>
   </message>

   <portType name="ProcessPT">
      <operation name="Run">
         <input message="proc:ProcessInputMessage"/>
         <output message="proc:ProcessOutputMessage"/>
      </operation>
   </portType>

   <binding name="ProcessBIND" type="proc:ProcessPT">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="Run">
         <soap:operation/>
         <input>
            <soap:body use="literal"/>
         </input>
         <output>
            <soap:body use="literal"/>
         </output>
      </operation>
   </binding>

   <binding name="CallbackBIND" type="resp:CallbackPT">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="Callback">
         <soap:operation/>
         <input>
            <soap:body use="literal"/>
         </input>
      </operation>
   </binding>

   <service name="ProcessSVC">
        <port name="ProcessPORT" binding="proc:ProcessBIND">
            <soap:address location="http://localhost:8080/ode/soap/async2/invoke"/>
        </port>
    <port name="CallbackPORT" binding="proc:CallbackBIND">
            <soap:address location="http://localhost:8080/ode/soap/async2/callback"/>
        </port>

   </service>

  <service name="ResponderSVC">
        <port name="ResponderPORT" binding="resp:ResponderBIND">
            <soap:address location="http://localhost:8080/ode/soap/async2/callback"/>
        </port>
   </service>

  <plnk:partnerLinkType name="ProcessCallerLT">
    <plnk:role name="Process" portType="proc:ProcessPT"/>
  </plnk:partnerLinkType>

</definitions>
