<?xml version="1.0" encoding="utf-8" ?>

<wsdl:definitions
    targetNamespace="http://ode/bpel/unit-test.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://ode/bpel/unit-test.wsdl"
    xmlns:resp="http://ode/bpel/responder.wsdl"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:bpws="http://schemas.xmlsoap.org/ws/2004/03/business-process/"
    xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/">

  <import namespace="http://ode/bpel/responder.wsdl" location="Responder.wsdl"/>

  <types>
    <xsd:element name="result" type="xsd:string"/>
  </types>

  <wsdl:message name="ResultMessage">
    <wsdl:part name="ack" element="tns:result"/>
  </wsdl:message>

  <wsdl:portType name="DynMainPortType">
    <wsdl:operation name="execute">
      <wsdl:input message="resp:DummyMessage" name="dummy"/>
      <wsdl:output message="tns:ResultMessage" name="result"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="DynMainBinding" type="tns:DynMainPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="execute">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:body namespace="http://ode/bpel/unit-test.wsdl" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body namespace="http://ode/bpel/unit-test.wsdl" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="DynMainService">
    <wsdl:port name="DynMainPort" binding="tns:DynMainBinding">
      <soap:address location="http://localhost:8080/ode/soap/dynmain"/>
    </wsdl:port>
  </wsdl:service>

  <plnk:partnerLinkType name="InitiatorPartnerLinkType">
      <plnk:role name="me" portType="tns:DynMainPortType"/>
  </plnk:partnerLinkType>

  <bpws:property name="dummyProp" type="xsd:string"/>
  <bpws:propertyAlias propertyName="tns:dummyProp" messageType="resp:DummyMessage"
                      part="payload"/>
  <bpws:propertyAlias propertyName="tns:dummyProp" messageType="resp:Dummy2Message"
                      part="payload"/> 

</wsdl:definitions>