<?xml version='1.0' encoding='utf-8'?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:pnlk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:this="http://example.com/ReproduceIsolationProblem/Pool2" xmlns:Pool3="http://example.com/ReproduceIsolationProblem/Pool3" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Pool="http://example.com/ReproduceIsolationProblem/Pool" xmlns:diag="http://example.com/ReproduceIsolationProblem" xmlns:xml="http://www.w3.org/XML/1998/namespace" targetNamespace="http://example.com/ReproduceIsolationProblem/Pool2">
    <wsdl:types>
        <xs:schema elementFormDefault="qualified" targetNamespace="http://example.com/ReproduceIsolationProblem/Pool2">
            <xs:element name="_21Request" type="xs:string"/>
            <xs:element name="_21Response" type="xs:string"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="_21Request">
        <wsdl:part name="body" element="this:_21Request"/>
    </wsdl:message>
    <wsdl:message name="_21Response">
        <wsdl:part name="body" element="this:_21Response"/>
    </wsdl:message>
    <wsdl:portType name="ForPool">
        <wsdl:operation name="_21">
            <wsdl:input message="this:_21Request" name="_21"/>
            <wsdl:output message="this:_21Response" name="_21Response"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CanonicBindingForPool" type="this:ForPool">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="_21">
            <soap:operation style="document" soapAction="http://example.com/ReproduceIsolationProblem/Pool2/ForPool/_21"/>
            <wsdl:input name="_21">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="_21Response">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CanonicServiceForPool">
        <wsdl:port name="canonicPort" binding="this:CanonicBindingForPool">
            <soap:address location="http://localhost:8080/ode/processes/Project-Reproduce-Isolation-Problem/ReproduceIsolationProblem/Pool2/Pool"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
