create table BPEL_ACTIVITY_RECOVERY (ID bigint not null auto_increment, PIID bigint, AID bigint, CHANNEL varchar(255), REASON varchar(255), DATE_TIME datetime, LDATA_ID bigint, ACTIONS varchar(255), RETRIES integer, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_CORRELATION_PROP (ID bigint not null auto_increment, NAME varchar(255), NAMESPACE varchar(255), VALUE varchar(255), CORR_SET_ID bigint, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_CORRELATION_SET (ID bigint not null auto_increment, VALUE varchar(255), CORR_SET_NAME varchar(255), SCOPE_ID bigint, PIID bigint, PROCESS_ID bigint, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_CORRELATOR (ID bigint not null auto_increment, CID varchar(255), PROCESS_ID bigint, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_CORRELATOR_MESSAGE_CKEY (ID bigint not null auto_increment, CKEY varchar(255), CORRELATOR_MESSAGE_ID bigint, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_EVENT (ID bigint not null auto_increment, IID bigint, PID bigint, TSTAMP datetime, TYPE varchar(255), DETAIL text, LDATA_ID bigint, SID bigint, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_FAULT (ID bigint not null auto_increment, FAULTNAME varchar(255), LDATA_ID bigint, EXPLANATION varchar(255), LINENO integer, AID integer, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_INSTANCE (ID bigint not null auto_increment, INSTANTIATING_CORRELATOR bigint, FAULT bigint, JACOB_STATE bigint, PREVIOUS_STATE smallint, PROCESS_ID bigint, STATE smallint, LAST_ACTIVE_DT datetime, SEQUENCE bigint, FAILURE_COUNT integer, FAILURE_DT datetime, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_MESSAGE (ID bigint not null auto_increment, MEX bigint, TYPE varchar(255), DATA bigint, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_MESSAGE_EXCHANGE (ID bigint not null auto_increment, PORT_TYPE varchar(255), CHANNEL_NAME varchar(255), CLIENTKEY varchar(255), LDATA_EPR_ID bigint, LDATA_CEPR_ID bigint, REQUEST bigint, RESPONSE bigint, INSERT_DT datetime, OPERATION varchar(255), STATE varchar(255), PROCESS bigint, PIID bigint, DIR char(1), PLINK_MODELID integer, PATTERN varchar(255), CORR_STATUS varchar(255), FAULT_TYPE varchar(255), FAULT_EXPL varchar(255), CALLEE varchar(255), PARTNERLINK bigint, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_MEX_PROPS (MEX bigint not null, VALUE varchar(8000), NAME varchar(255) not null, primary key (MEX, NAME));
create table BPEL_PLINK_VAL (ID bigint not null auto_increment, PARTNER_LINK varchar(100) not null, PARTNERROLE varchar(100), MYROLE_EPR bigint, PARTNERROLE_EPR bigint, PROCESS bigint, SCOPE bigint, SVCNAME varchar(255), MYROLE varchar(100), MODELID integer, MYSESSIONID varchar(255), PARTNERSESSIONID varchar(255), INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_PROCESS (ID bigint not null auto_increment, PROCID varchar(255) not null unique, deployer varchar(255), deploydate datetime, type_name varchar(255), type_ns varchar(255), version integer, RETIRED bit, ACTIVE bit, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_PROCESS_CONF (ID bigint not null auto_increment, PROCID varchar(255) not null unique, deployer varchar(255), deploydate datetime, type_name varchar(255), type_ns varchar(255), version integer, ACTIVE bit, primary key (ID));
create table BPEL_PROCESS_PROPERTY (ID bigint not null auto_increment, PROPNAME varchar(255), PROPNS varchar(255), SIMPLE_CNT varchar(255), MIXED_CNT longtext, PROCESS_ID bigint, primary key (ID));
create table BPEL_SCOPE (ID bigint not null auto_increment, PIID bigint, PARENT_SCOPE_ID bigint, STATE varchar(255) not null, NAME varchar(255) not null, MODELID integer, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_SELECTORS (ID bigint not null auto_increment, PIID bigint not null, SELGRPID varchar(255) not null, IDX integer not null, CORRELATION_KEY varchar(255) not null, CORRELATOR bigint not null, INSERT_TIME datetime, MLOCK integer not null, primary key (ID), unique (CORRELATION_KEY, CORRELATOR));
create table BPEL_UNMATCHED (ID bigint not null auto_increment, MEX bigint not null, CORRELATION_KEY varchar(255), CORRELATOR bigint not null, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table BPEL_XML_DATA (ID bigint not null auto_increment, LDATA_ID bigint, NAME varchar(255) not null, SCOPE_ID bigint, PIID bigint, IS_SIMPLE_TYPE bit, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table LARGE_DATA (ID bigint not null auto_increment, BIN_DATA blob, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
create table VAR_PROPERTY (ID bigint not null auto_increment, XML_DATA_ID bigint, PROP_VALUE varchar(255), PROP_NAME varchar(255) not null, INSERT_TIME datetime, MLOCK integer not null, primary key (ID));
alter table BPEL_ACTIVITY_RECOVERY add index FK94D24A7BEBD59315 (LDATA_ID), add constraint FK94D24A7BEBD59315 foreign key (LDATA_ID) references LARGE_DATA (ID);
alter table BPEL_ACTIVITY_RECOVERY add index FK94D24A7BA821BBE1 (PIID), add constraint FK94D24A7BA821BBE1 foreign key (PIID) references BPEL_INSTANCE (ID);
alter table BPEL_CORRELATION_PROP add index FK4EC9DDAA4D0B7982 (CORR_SET_ID), add constraint FK4EC9DDAA4D0B7982 foreign key (CORR_SET_ID) references BPEL_CORRELATION_SET (ID);
alter table BPEL_CORRELATION_SET add index FKB838191BA821BBE1 (PIID), add constraint FKB838191BA821BBE1 foreign key (PIID) references BPEL_INSTANCE (ID);
alter table BPEL_CORRELATION_SET add index FKB838191B6D49C363 (SCOPE_ID), add constraint FKB838191B6D49C363 foreign key (SCOPE_ID) references BPEL_SCOPE (ID);
alter table BPEL_CORRELATION_SET add index FKB838191BE15A2343 (PROCESS_ID), add constraint FKB838191BE15A2343 foreign key (PROCESS_ID) references BPEL_PROCESS (ID);
create index IDX_CORRELATOR_CID on BPEL_CORRELATOR (CID);
alter table BPEL_CORRELATOR add index FKF50EFA33E15A2343 (PROCESS_ID), add constraint FKF50EFA33E15A2343 foreign key (PROCESS_ID) references BPEL_PROCESS (ID);
create index IDX_BPEL_CORRELATOR_MESSAGE_CKEY on BPEL_CORRELATOR_MESSAGE_CKEY (CKEY);
alter table BPEL_CORRELATOR_MESSAGE_CKEY add index FK8997F700EEFA7470 (CORRELATOR_MESSAGE_ID), add constraint FK8997F700EEFA7470 foreign key (CORRELATOR_MESSAGE_ID) references BPEL_UNMATCHED (ID);
alter table BPEL_EVENT add index FKAA6D6730EBD59315 (LDATA_ID), add constraint FKAA6D6730EBD59315 foreign key (LDATA_ID) references LARGE_DATA (ID);
alter table BPEL_EVENT add index FKAA6D6730A7EED251 (IID), add constraint FKAA6D6730A7EED251 foreign key (IID) references BPEL_INSTANCE (ID);
alter table BPEL_EVENT add index FKAA6D6730C831CBE3 (PID), add constraint FKAA6D6730C831CBE3 foreign key (PID) references BPEL_PROCESS (ID);
alter table BPEL_FAULT add index FKAA722EB8EBD59315 (LDATA_ID), add constraint FKAA722EB8EBD59315 foreign key (LDATA_ID) references LARGE_DATA (ID);
alter table BPEL_INSTANCE add index FKE1DED41FDD43DBE1 (INSTANTIATING_CORRELATOR), add constraint FKE1DED41FDD43DBE1 foreign key (INSTANTIATING_CORRELATOR) references BPEL_CORRELATOR (ID);
alter table BPEL_INSTANCE add index FKE1DED41F433A5462 (JACOB_STATE), add constraint FKE1DED41F433A5462 foreign key (JACOB_STATE) references LARGE_DATA (ID);
alter table BPEL_INSTANCE add index FKE1DED41F1F3C9CB7 (FAULT), add constraint FKE1DED41F1F3C9CB7 foreign key (FAULT) references BPEL_FAULT (ID);
alter table BPEL_INSTANCE add index FKE1DED41FE15A2343 (PROCESS_ID), add constraint FKE1DED41FE15A2343 foreign key (PROCESS_ID) references BPEL_PROCESS (ID);
alter table BPEL_MESSAGE add index FK4FA7231DCA00A413 (MEX), add constraint FK4FA7231DCA00A413 foreign key (MEX) references BPEL_MESSAGE_EXCHANGE (ID);
alter table BPEL_MESSAGE add index FK4FA7231DC3002ADB (DATA), add constraint FK4FA7231DC3002ADB foreign key (DATA) references LARGE_DATA (ID);
alter table BPEL_MESSAGE_EXCHANGE add index FKBDA6BD0561AB335E (LDATA_CEPR_ID), add constraint FKBDA6BD0561AB335E foreign key (LDATA_CEPR_ID) references LARGE_DATA (ID);
alter table BPEL_MESSAGE_EXCHANGE add index FKBDA6BD05BBA250D (PARTNERLINK), add constraint FKBDA6BD05BBA250D foreign key (PARTNERLINK) references BPEL_PLINK_VAL (ID);
alter table BPEL_MESSAGE_EXCHANGE add index FKBDA6BD05A821BBE1 (PIID), add constraint FKBDA6BD05A821BBE1 foreign key (PIID) references BPEL_INSTANCE (ID);
alter table BPEL_MESSAGE_EXCHANGE add index FKBDA6BD059A69FCAD (LDATA_EPR_ID), add constraint FKBDA6BD059A69FCAD foreign key (LDATA_EPR_ID) references LARGE_DATA (ID);
alter table BPEL_MESSAGE_EXCHANGE add index FKBDA6BD05B5BD38C7 (PROCESS), add constraint FKBDA6BD05B5BD38C7 foreign key (PROCESS) references BPEL_PROCESS (ID);
alter table BPEL_MESSAGE_EXCHANGE add index FKBDA6BD05FF451031 (RESPONSE), add constraint FKBDA6BD05FF451031 foreign key (RESPONSE) references BPEL_MESSAGE (ID);
alter table BPEL_MESSAGE_EXCHANGE add index FKBDA6BD0554DCEE7F (REQUEST), add constraint FKBDA6BD0554DCEE7F foreign key (REQUEST) references BPEL_MESSAGE (ID);
alter table BPEL_MEX_PROPS add index FK203CAFC7CA00A413 (MEX), add constraint FK203CAFC7CA00A413 foreign key (MEX) references BPEL_MESSAGE_EXCHANGE (ID);
alter table BPEL_PLINK_VAL add index FK7D71E742CA8FEABB (MYROLE_EPR), add constraint FK7D71E742CA8FEABB foreign key (MYROLE_EPR) references LARGE_DATA (ID);
alter table BPEL_PLINK_VAL add index FK7D71E74290D95ED1 (SCOPE), add constraint FK7D71E74290D95ED1 foreign key (SCOPE) references BPEL_SCOPE (ID);
alter table BPEL_PLINK_VAL add index FK7D71E742B5BD38C7 (PROCESS), add constraint FK7D71E742B5BD38C7 foreign key (PROCESS) references BPEL_PROCESS (ID);
alter table BPEL_PLINK_VAL add index FK7D71E742AC89DDD7 (PARTNERROLE_EPR), add constraint FK7D71E742AC89DDD7 foreign key (PARTNERROLE_EPR) references LARGE_DATA (ID);
alter table BPEL_PROCESS_PROPERTY add index FK4690A34F5F2D4DD4 (PROCESS_ID), add constraint FK4690A34F5F2D4DD4 foreign key (PROCESS_ID) references BPEL_PROCESS_CONF (ID);
alter table BPEL_SCOPE add index FKAB2A32EAA821BBE1 (PIID), add constraint FKAB2A32EAA821BBE1 foreign key (PIID) references BPEL_INSTANCE (ID);
alter table BPEL_SCOPE add index FKAB2A32EA42B20B58 (PARENT_SCOPE_ID), add constraint FKAB2A32EA42B20B58 foreign key (PARENT_SCOPE_ID) references BPEL_SCOPE (ID);
create index IDX_SELECTOR_CORRELATOR on BPEL_SELECTORS (CORRELATOR);
create index IDX_SELECTOR_CKEY on BPEL_SELECTORS (CORRELATION_KEY);
create index IDX_SELECTOR_SELGRPID on BPEL_SELECTORS (SELGRPID);
alter table BPEL_SELECTORS add index FKF1F83A0AA821BBE1 (PIID), add constraint FKF1F83A0AA821BBE1 foreign key (PIID) references BPEL_INSTANCE (ID);
alter table BPEL_SELECTORS add index FKF1F83A0A875201C9 (CORRELATOR), add constraint FKF1F83A0A875201C9 foreign key (CORRELATOR) references BPEL_CORRELATOR (ID);
create index IDX_UNMATCHED_CKEY on BPEL_UNMATCHED (CORRELATION_KEY);
create index IDX_UNMATCHED_CORRELATOR on BPEL_UNMATCHED (CORRELATOR);
alter table BPEL_UNMATCHED add index FKF0663E01CA00A413 (MEX), add constraint FKF0663E01CA00A413 foreign key (MEX) references BPEL_MESSAGE_EXCHANGE (ID);
alter table BPEL_UNMATCHED add index FKF0663E01875201C9 (CORRELATOR), add constraint FKF0663E01875201C9 foreign key (CORRELATOR) references BPEL_CORRELATOR (ID);
alter table BPEL_XML_DATA add index FKB7D47E7CEBD59315 (LDATA_ID), add constraint FKB7D47E7CEBD59315 foreign key (LDATA_ID) references LARGE_DATA (ID);
alter table BPEL_XML_DATA add index FKB7D47E7CA821BBE1 (PIID), add constraint FKB7D47E7CA821BBE1 foreign key (PIID) references BPEL_INSTANCE (ID);
alter table BPEL_XML_DATA add index FKB7D47E7C6D49C363 (SCOPE_ID), add constraint FKB7D47E7C6D49C363 foreign key (SCOPE_ID) references BPEL_SCOPE (ID);
alter table VAR_PROPERTY add index FK9C1E2C0DA48E25F2 (XML_DATA_ID), add constraint FK9C1E2C0DA48E25F2 foreign key (XML_DATA_ID) references BPEL_XML_DATA (ID);
#
# In your Quartz properties file, you'll need to set 
# org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#
#
# By: Ron Cordell - roncordell
#  I didn't see this anywhere, so I thought I'd post it here. This is the script from Quartz to create the tables in a MySQL database, modified to use INNODB instead of MYISAM.

DROP TABLE IF EXISTS QRTZ_JOB_LISTENERS;
DROP TABLE IF EXISTS QRTZ_TRIGGER_LISTENERS;
DROP TABLE IF EXISTS QRTZ_FIRED_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE;
DROP TABLE IF EXISTS QRTZ_LOCKS;
DROP TABLE IF EXISTS QRTZ_SIMPLE_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_JOB_DETAILS;
DROP TABLE IF EXISTS QRTZ_CALENDARS;
CREATE TABLE QRTZ_JOB_DETAILS(
JOB_NAME VARCHAR(80) NOT NULL,
JOB_GROUP VARCHAR(80) NOT NULL,
DESCRIPTION VARCHAR(120) NULL,
JOB_CLASS_NAME VARCHAR(128) NOT NULL,
IS_DURABLE VARCHAR(1) NOT NULL,
IS_VOLATILE VARCHAR(1) NOT NULL,
IS_STATEFUL VARCHAR(1) NOT NULL,
REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
JOB_DATA BLOB NULL,
PRIMARY KEY (JOB_NAME,JOB_GROUP))
TYPE=InnoDB;

CREATE TABLE QRTZ_JOB_LISTENERS (
JOB_NAME VARCHAR(80) NOT NULL,
JOB_GROUP VARCHAR(80) NOT NULL,
JOB_LISTENER VARCHAR(80) NOT NULL,
PRIMARY KEY (JOB_NAME,JOB_GROUP,JOB_LISTENER),
INDEX (JOB_NAME, JOB_GROUP),
FOREIGN KEY (JOB_NAME,JOB_GROUP)
REFERENCES QRTZ_JOB_DETAILS(JOB_NAME,JOB_GROUP))
TYPE=InnoDB;

CREATE TABLE QRTZ_TRIGGERS (
TRIGGER_NAME VARCHAR(80) NOT NULL,
TRIGGER_GROUP VARCHAR(80) NOT NULL,
JOB_NAME VARCHAR(80) NOT NULL,
JOB_GROUP VARCHAR(80) NOT NULL,
IS_VOLATILE VARCHAR(1) NOT NULL,
DESCRIPTION VARCHAR(120) NULL,
NEXT_FIRE_TIME BIGINT(13) NULL,
PREV_FIRE_TIME BIGINT(13) NULL,
TRIGGER_STATE VARCHAR(16) NOT NULL,
TRIGGER_TYPE VARCHAR(8) NOT NULL,
START_TIME BIGINT(13) NOT NULL,
END_TIME BIGINT(13) NULL,
CALENDAR_NAME VARCHAR(80) NULL,
MISFIRE_INSTR SMALLINT(2) NULL,
JOB_DATA BLOB NULL,
PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
INDEX (JOB_NAME, JOB_GROUP),
FOREIGN KEY (JOB_NAME,JOB_GROUP)
REFERENCES QRTZ_JOB_DETAILS(JOB_NAME,JOB_GROUP))
TYPE=InnoDB;

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
TRIGGER_NAME VARCHAR(80) NOT NULL,
TRIGGER_GROUP VARCHAR(80) NOT NULL,
REPEAT_COUNT BIGINT(7) NOT NULL,
REPEAT_INTERVAL BIGINT(12) NOT NULL,
TIMES_TRIGGERED BIGINT(7) NOT NULL,
PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
INDEX (TRIGGER_NAME, TRIGGER_GROUP),
FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP))
TYPE=InnoDB;

CREATE TABLE QRTZ_CRON_TRIGGERS (
TRIGGER_NAME VARCHAR(80) NOT NULL,
TRIGGER_GROUP VARCHAR(80) NOT NULL,
CRON_EXPRESSION VARCHAR(80) NOT NULL,
TIME_ZONE_ID VARCHAR(80),
PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
INDEX (TRIGGER_NAME, TRIGGER_GROUP),
FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP))
TYPE=InnoDB;

CREATE TABLE QRTZ_BLOB_TRIGGERS (
TRIGGER_NAME VARCHAR(80) NOT NULL,
TRIGGER_GROUP VARCHAR(80) NOT NULL,
BLOB_DATA BLOB NULL,
PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP),
INDEX (TRIGGER_NAME, TRIGGER_GROUP),
FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP))
TYPE=InnoDB;

CREATE TABLE QRTZ_TRIGGER_LISTENERS (
TRIGGER_NAME VARCHAR(80) NOT NULL,
TRIGGER_GROUP VARCHAR(80) NOT NULL,
TRIGGER_LISTENER VARCHAR(80) NOT NULL,
PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_LISTENER),
INDEX (TRIGGER_NAME, TRIGGER_GROUP),
FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP))
TYPE=InnoDB;

CREATE TABLE QRTZ_CALENDARS (
CALENDAR_NAME VARCHAR(80) NOT NULL,
CALENDAR BLOB NOT NULL,
PRIMARY KEY (CALENDAR_NAME))
TYPE=InnoDB;

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
TRIGGER_GROUP VARCHAR(80) NOT NULL,
PRIMARY KEY (TRIGGER_GROUP))
TYPE=InnoDB;

CREATE TABLE QRTZ_FIRED_TRIGGERS (
ENTRY_ID VARCHAR(95) NOT NULL,
TRIGGER_NAME VARCHAR(80) NOT NULL,
TRIGGER_GROUP VARCHAR(80) NOT NULL,
IS_VOLATILE VARCHAR(1) NOT NULL,
INSTANCE_NAME VARCHAR(80) NOT NULL,
FIRED_TIME BIGINT(13) NOT NULL,
STATE VARCHAR(16) NOT NULL,
JOB_NAME VARCHAR(80) NULL,
JOB_GROUP VARCHAR(80) NULL,
IS_STATEFUL VARCHAR(1) NULL,
REQUESTS_RECOVERY VARCHAR(1) NULL,
PRIMARY KEY (ENTRY_ID))
TYPE=InnoDB;

CREATE TABLE QRTZ_SCHEDULER_STATE (
INSTANCE_NAME VARCHAR(80) NOT NULL,
LAST_CHECKIN_TIME BIGINT(13) NOT NULL,
CHECKIN_INTERVAL BIGINT(13) NOT NULL,
RECOVERER VARCHAR(80) NULL,
PRIMARY KEY (INSTANCE_NAME))
TYPE=InnoDB;

CREATE TABLE QRTZ_LOCKS (
LOCK_NAME VARCHAR(40) NOT NULL,
PRIMARY KEY (LOCK_NAME))
TYPE=InnoDB;

INSERT INTO QRTZ_LOCKS values('TRIGGER_ACCESS');
INSERT INTO QRTZ_LOCKS values('JOB_ACCESS');
INSERT INTO QRTZ_LOCKS values('CALENDAR_ACCESS');
INSERT INTO QRTZ_LOCKS values('STATE_ACCESS');
INSERT INTO QRTZ_LOCKS values('MISFIRE_ACCESS');
commit; 
