/*
 * Created on Dec 9, 2004
 *
 */
package org.opentools.minerva.jdbc;

/**
 * Wrapper for prepared statement args; needed for
 * comparison of different prepared statements with different
 * settings; required for statement caching.
 */
public class PreparedStatementArgs {
	String sql;
  Integer autoGeneratedKeys;
  /**
	 * 
	 */
	public PreparedStatementArgs(String sql) {
		this.sql = sql;
	}
  
  PreparedStatementArgs(String sql, int autoGeneratedKeys){
  	this(sql);
    this.autoGeneratedKeys = Integer.valueOf(autoGeneratedKeys);
  }
  
  public boolean equals(Object obj){
    PreparedStatementArgs a = (PreparedStatementArgs)obj;
    return (sql.equals(a.sql))
      && (autoGeneratedKeys == a.autoGeneratedKeys
          || (autoGeneratedKeys != null 
              && a.autoGeneratedKeys != null 
              && autoGeneratedKeys.equals(a.autoGeneratedKeys)));
  }
  
  public int hashCode(){
  	return sql.hashCode() 
      + (autoGeneratedKeys == null ? 0 : autoGeneratedKeys.hashCode());
  }
}
