<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:ns0="http://axis2.ode.apache.org/xsd"
                  xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
                  xmlns:ns1="http://axis2.ode.apache.org"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  targetNamespace="http://axis2.ode.apache.org">
   <wsdl:types>
      <xs:schema xmlns:ns="http://axis2.ode.apache.org" attributeFormDefault="qualified"
                 elementFormDefault="unqualified" targetNamespace="http://axis2.ode.apache.org">
         <xs:element name="noArgmentMethodResponse">
            <xs:complexType>
               <xs:sequence>
                  <xs:element minOccurs="0" name="return" nillable="true" type="xs:string"/>
               </xs:sequence>
            </xs:complexType>
         </xs:element>

      </xs:schema>
   </wsdl:types>
   <wsdl:message name="noArgmentMethodResponse">
      <wsdl:part name="parameters" element="ns1:noArgmentMethodResponse"/>
   </wsdl:message>
   <wsdl:portType name="DummyServicePortType">
      <wsdl:operation name="noArgmentMethod">
         <wsdl:output message="ns1:noArgmentMethodResponse" wsaw:Action="urn:noArgmentMethodResponse"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="DummyServiceSOAP11Binding" type="ns1:DummyServicePortType">
      <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
       <wsdl:operation name="noArgmentMethod">
         <soap:operation soapAction="urn:noArgmentMethod" style="document"/>
         <wsdl:output>
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="DummyService">
      <wsdl:port name="DummyServiceSOAP11port_http" binding="ns1:DummyServiceSOAP11Binding">
         <soap:address location="http://localhost:8888/ode/processes/DummyService"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
