<?xml version="1.0"?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<definitions name="Hello"
        targetNamespace="urn:/HelloWorld2-RPC.wsdl"
        xmlns:tns="urn:/HelloWorld2-RPC.wsdl"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns="http://schemas.xmlsoap.org/wsdl/">

    <message name="HelloRequest">
        <part name="text" type="xsd:string"/>
    </message>

    <message name="HelloResponse">
        <part name="text" type="xsd:string"/>
    </message>

    <portType name="HelloPortType">
        <operation name="Hello">
            <input message="tns:HelloRequest"/>
            <output message="tns:HelloResponse"/>
        </operation>
    </portType>

    <plnk:partnerLinkType name="HelloPartnerLinkType">
        <plnk:role name="Provider" portType="tns:HelloPortType"/>
    </plnk:partnerLinkType>

    <!--

    This is an abstract interface/portType definition.  Note the lack of
    binding and service: these are defined by the HTTP binding component.
    See HelloWorld2-RPC-http/HelloWorld2-RPC.wsdl for details.

    -->

</definitions>

