<?xml version='1.0' encoding='utf-8'?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" 
xmlns:pnlk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" 
xmlns:xml="http://www.w3.org/XML/1998/namespace" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:this="http://example.com/CircularReference2" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
targetNamespace="http://example.com/CircularReference2">
    <wsdl:types>
        <xs:schema elementFormDefault="qualified" targetNamespace="urn:targetnm">
            <xs:element name="EventStartMessageRequest1" type="xs:string"/>
            <xs:element name="EventStartMessageResponse1" type="xs:string"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:import namespace="http://example.com/CircularReference1" location="CircularReference1.wsdl"/>
    <wsdl:message name="EventStartMessageRequest1">
        <wsdl:part name="body" element="this:EventStartMessageRequest1"/>
    </wsdl:message>
    <wsdl:message name="EventStartMessageResponse1">
        <wsdl:part name="body" element="this:EventStartMessageResponse1"/>
    </wsdl:message>
    <wsdl:portType name="portType1">
        <wsdl:operation name="EventStartMessage1">
            <wsdl:input message="this:EventStartMessageRequest1" name="EventStartMessage1"/>
            <wsdl:output message="this:EventStartMessageResponse1" name="EventStartMessageResponse1"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="binding1" type="this:portType1">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="EventStartMessage1">
            <soap:operation style="document" soapAction="http://www.example.com/eventStartMessage"/>
            <wsdl:input name="EventStartMessage1">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="EventStartMessageResponse1">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="service1">
        <wsdl:port name="servicePort" binding="this:binding1">
            <soap:address location="http://example.com/hello"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
