<?xml version="1.0" ?>

<!-- The probe service is a simple extension that concatenates two strings -->
<!-- The probeName part is concatenated to the end of the probeData part -->
<!-- and the probeData part is returned as output. -->
<!-- The service is used to facilitate chicken track debugging of BPEL -->

<wsdl:definitions targetNamespace="http://ode/bpel/unit-test/ProbeService.wsdl"
   xmlns:tns="http://ode/bpel/unit-test/ProbeService.wsdl"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns="http://ode/bpel/unit-test/ProbeService.wsdl">


  <!-- message declns -->

  <wsdl:message name="probeMessage">
     <wsdl:part name="probeName" type="xsd:string"/>
     <wsdl:part name="probeData" type="xsd:string"/>
  </wsdl:message>


  <!-- port type declns -->
   <wsdl:portType name="probeMessagePT">
      <wsdl:operation name="probe">
         <wsdl:input name="ProbeInputMessage" message="tns:probeMessage"/>
         <wsdl:output name="ProbeOutputMessage" message="tns:probeMessage"/>
      </wsdl:operation>

   </wsdl:portType>

</wsdl:definitions>

