<?xml version="1.0"?>
<definitions name="Hello"
        targetNamespace="urn:/HelloWorld2.wsdl"
        xmlns:tns="urn:/HelloWorld2.wsdl"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:smix="http://servicemix.org/wsdl/jbi/"
        xmlns="http://schemas.xmlsoap.org/wsdl/">

    <types>
        <schema targetNamespace="urn:/HelloWorld2.wsdl"
                xmlns="http://www.w3.org/2000/10/XMLSchema">
            <element name="HelloRequest">
                <complexType>
                    <all>
                        <element name="text" type="string"/>
                    </all>
                </complexType>
            </element>
            <element name="HelloResponse">
                <complexType>
                    <all>
                        <element name="text" type="string"/>
                    </all>
                </complexType>
            </element>
        </schema>
    </types>

    <message name="HelloRequest">
        <part name="body" element="tns:HelloRequest"/>
    </message>

    <message name="HelloResponse">
        <part name="body" element="tns:HelloResponse"/>
    </message>

    <portType name="HelloPortType">
        <operation name="Hello">
            <input message="tns:HelloRequest"/>
            <output message="tns:HelloResponse"/>
        </operation>
    </portType>

    <binding name="HelloSoapBinding" type="tns:HelloPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Hello">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="HelloService">
        <port name="HelloPort" binding="tns:HelloSoapBinding">
            <soap:address location="http://localhost:8080/hello-doc"/>

            <!-- Connect this external HTTP endpoint to the process internal 
                 JBI endpoint defined in HelloWorld2-process/HelloWorld2.dd -->
            <smix:endpoint role="consumer" defaultMep="in-out"/>

        </port>
    </service>

</definitions>
