/* Generated By:JJTree: Do not edit this line. ASTAnd.java */

package com.fs.pxe.ql.jcc;

public class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
  }

  public ASTAnd(QLParser p, int id) {
    super(p, id);
  }

}
