/* Generated By:JJTree: Do not edit this line. ASTEqual.java */

package com.fs.pxe.ql.jcc;

public class ASTEqual extends SimpleNode {
  public ASTEqual(int id) {
    super(id);
  }

  public ASTEqual(QLParser p, int id) {
    super(p, id);
  }

}
