/* Generated By:JJTree: Do not edit this line. ASTGreater.java */

package com.fs.pxe.ql.jcc;

public class ASTGreater extends SimpleNode {
  public ASTGreater(int id) {
    super(id);
  }

  public ASTGreater(QLParser p, int id) {
    super(p, id);
  }

}
