/* Generated By:JJTree: Do not edit this line. ASTGE.java */

package com.fs.pxe.ql.jcc;

public class ASTGE extends SimpleNode {
  public ASTGE(int id) {
    super(id);
  }

  public ASTGE(QLParser p, int id) {
    super(p, id);
  }

}
