/* Generated By:JJTree: Do not edit this line. ASTLike.java */

package com.fs.pxe.ql.jcc;

public class ASTLike extends SimpleNode {
  public ASTLike(int id) {
    super(id);
  }

  public ASTLike(QLParser p, int id) {
    super(p, id);
  }

}
