/* Generated By:JJTree: Do not edit this line. ASTLE.java */

package com.fs.pxe.ql.jcc;

public class ASTLE extends SimpleNode {
  public ASTLE(int id) {
    super(id);
  }

  public ASTLE(QLParser p, int id) {
    super(p, id);
  }

}
