/* Generated By:JJTree: Do not edit this line. ASTLess.java */

package com.fs.pxe.ql.jcc;

public class ASTLess extends SimpleNode {
  public ASTLess(int id) {
    super(id);
  }

  public ASTLess(QLParser p, int id) {
    super(p, id);
  }

}
