/* Generated By:JJTree: Do not edit this line. ASTOrderByField.java */

package com.fs.pxe.ql.jcc;

public class ASTOrderByField extends SimpleNode {
  public ASTOrderByField(int id) {
    super(id);
  }

  public ASTOrderByField(QLParser p, int id) {
    super(p, id);
  }

}
