/* Generated By:JJTree: Do not edit this line. ASTOr.java */

package com.fs.pxe.ql.jcc;

public class ASTOr extends SimpleNode {
  public ASTOr(int id) {
    super(id);
  }

  public ASTOr(QLParser p, int id) {
    super(p, id);
  }

}
