<?xml version="1.0"?>
<definitions name="Hello"
        targetNamespace="urn:/HelloWorld2.wsdl"
        xmlns:tns="urn:/HelloWorld2.wsdl"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/"
        xmlns="http://schemas.xmlsoap.org/wsdl/">

    <types>
        <schema targetNamespace="urn:/HelloWorld2.wsdl"
                xmlns="http://www.w3.org/2000/10/XMLSchema">
            <element name="HelloRequest">
                <complexType>
                    <all>
                        <element name="text" type="string"/>
                    </all>
                </complexType>
            </element>
            <element name="HelloResponse">
                <complexType>
                    <all>
                        <element name="text" type="string"/>
                    </all>
                </complexType>
            </element>
        </schema>
    </types>

    <message name="HelloRequest">
        <part name="body" element="tns:HelloRequest"/>
    </message>

    <message name="HelloResponse">
        <part name="body" element="tns:HelloResponse"/>
    </message>

    <portType name="HelloPortType">
        <operation name="Hello">
            <input message="tns:HelloRequest"/>
            <output message="tns:HelloResponse"/>
        </operation>
    </portType>

    <plnk:partnerLinkType name="HelloPartnerLinkType">
        <plnk:role name="Provider" portType="tns:HelloPortType"/>
    </plnk:partnerLinkType>
    
    <!--
    
    This is an abstract interface/portType definition.  Note the lack of 
    binding and service: these are defined by the HTTP binding component.
    See HelloWorld2-http/HelloWorld2.wsdl for details.
    
    -->

</definitions>
