<?xml version='1.0' encoding='utf-8'?>
<wsdl:definitions xmlns:bpdm="http://www.intalio/designer/business-process-data-modeling" xmlns:Pool="http://example.com/ForEach/Pool" xmlns:ForEach="http://example.com/ForEach/ForEach" xmlns:diag="http://example.com/ForEach" xmlns:bpel="http://schemas.xmlsoap.org/ws/2004/03/business-process/" xmlns:pnlk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:foreach="http://www.example.org/jms" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://example.com/ForEach">
    <wsdl:import namespace="http://example.com/ForEach/ForEach" location="ForEach-ForEach.wsdl"/>
    <pnlk:partnerLinkType name="PoolAndForEach">
        <pnlk:role name="ForEach_for_Pool" portType="ForEach:ForPool"/>
    </pnlk:partnerLinkType>
</wsdl:definitions>