<?xml version='1.0' encoding='utf-8'?>
<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements.  See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership.  The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License.  You may obtain a copy of the License at
  ~
  ~    http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied.  See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<wsdl:definitions xmlns:Pool="http://example.com/ForEach/Pool" xmlns:diag="http://example.com/ForEach" xmlns:bpel="http://schemas.xmlsoap.org/ws/2004/03/business-process/" xmlns:pnlk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:foreach="http://www.example.org/jms" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:this="http://example.com/ForEach/ForEach" targetNamespace="http://example.com/ForEach/ForEach">
    <wsdl:types>
        <xs:schema targetNamespace="http://www.example.org/jms">
            <xs:include schemaLocation="foreach.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="startRequest">
        <wsdl:part name="body" element="foreach:input"/>
    </wsdl:message>
    <wsdl:message name="startResponse">
        <wsdl:part name="body" element="foreach:input"/>
    </wsdl:message>
    <wsdl:portType name="ForPool">
        <wsdl:operation name="start">
            <wsdl:input message="this:startRequest" name="start"/>
            <wsdl:output message="this:startResponse" name="startResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CanonicBindingForPool" type="this:ForPool">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="start">
            <soap:operation style="document" soapAction="http://example.com/ForEach/ForEach/ForPool/start"/>
            <wsdl:input><soap:body use="literal"/></wsdl:input>
            <wsdl:output><soap:body use="literal"/></wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CanonicServiceForPool">
        <wsdl:port name="canonicPort" binding="this:CanonicBindingForPool">
            <soap:address location="http://localhost:8080/ode/processes/ForEach/Pool"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>